 name = "telegram-bot-worker"
main = "index.js"
compatibility_date = "2024-01-15"

[vars]
# TOKEN BOT TELEGRAM
BOT_TOKEN = "8178123942:AAGZaNxo-8HajTk7LIM3rVn_N_0zTq7LNBM"

# ADMIN
ADMIN_ID = "6403937911"
ADMIN_USERNAME = "@TeamNexusDev"

# API Deposit QR Baru
API_CREATE_URL = "https://my-payment.autsc.my.id/api/deposit"
API_CHECK_PAYMENT = "https://my-payment.autsc.my.id/api/status/payment"
PAYMENT_API_KEY = "b67ff890-491c-4732-9ed4-453514fcccaa"

# Pengaturan Nominal Deposit
MIN_AMOUNT = "1000"
RANDOM_AMOUNT_MIN = "1"
RANDOM_AMOUNT_MAX = "100"

# Database (KV Storage)
[[kv_namespaces]]
binding = "BOT_DB"
id = "73f35115537f40ed8263ea8656f1166a"
preview_id = "73f35115537f40ed8263ea8656f1166a"
